//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arquivo
    {
        public System.Guid IdArquivo { get; set; }
        public int IdRepositorio { get; set; }
        public string Tipo { get; set; }
        public string Nome { get; set; }
        public string Metadado { get; set; }
        public decimal TamanhoBytes { get; set; }
        public byte[] Arquivo1 { get; set; }
        public System.DateTime Registro { get; set; }
        public Nullable<System.DateTime> Alteracao { get; set; }
        public bool Ativo { get; set; }
    
        public virtual Repositorio Repositorio { get; set; }
    }
}
