//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class THistoricoTransferencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public THistoricoTransferencia()
        {
            this.TBlocoTransferencia = new HashSet<TBlocoTransferencia>();
        }
    
        public System.Guid IDHistoricoTransferencia { get; set; }
        public System.Guid IDRepositorioSistemaClienteOrigem { get; set; }
        public Nullable<System.Guid> IDRepositorioSistemaClienteDestino { get; set; }
        public System.DateTime DataHoraInicioTransferencia { get; set; }
        public Nullable<System.DateTime> DataHoraTerminoTransferencia { get; set; }
        public Nullable<bool> TransferenciaOK { get; set; }
        public Nullable<int> QtdIndices { get; set; }
        public string Error { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBlocoTransferencia> TBlocoTransferencia { get; set; }
    }
}
