//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRepositSistemaCliente
    {
        public System.Guid IDRepositSistemaCliente { get; set; }
        public System.Guid IDRepositorio { get; set; }
        public Nullable<int> PrazoRetencaoDias { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public bool Ativo { get; set; }
        public System.Guid IDSistemaCliente { get; set; }
    
        public virtual TRepositorio TRepositorio { get; set; }
        public virtual TSistemaCliente TSistemaCliente { get; set; }
    }
}
