//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GerenciadorContexto : DbContext
    {
        public GerenciadorContexto()
            : base("name=GerenciadorContexto")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TCliente> TCliente { get; set; }
        public virtual DbSet<TRepositorio> TRepositorio { get; set; }
        public virtual DbSet<TRepositSistemaCliente> TRepositSistemaCliente { get; set; }
        public virtual DbSet<TSistema> TSistema { get; set; }
        public virtual DbSet<TSistemaCliente> TSistemaCliente { get; set; }
        public virtual DbSet<TArquivoTransferencia> TArquivoTransferencia { get; set; }
        public virtual DbSet<TBlocoTransferencia> TBlocoTransferencia { get; set; }
        public virtual DbSet<THistoricoTransferencia> THistoricoTransferencia { get; set; }
        public virtual DbSet<TIndice> TIndice { get; set; }
    }
}
