//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBlocoTransferencia
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBlocoTransferencia()
        {
            this.TArquivoTransferencia = new HashSet<TArquivoTransferencia>();
        }
    
        public System.Guid IdBlocoTranferencia { get; set; }
        public System.DateTime DataHoraInicioTransferencia { get; set; }
        public Nullable<System.DateTime> DataHoraTerminoTransferencia { get; set; }
        public bool TranferenciaOK { get; set; }
        public decimal TamanhoBytes { get; set; }
        public System.Guid IdHistoricoTransferencia { get; set; }
        public string Error { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TArquivoTransferencia> TArquivoTransferencia { get; set; }
        public virtual THistoricoTransferencia THistoricoTransferencia { get; set; }
    }
}
