//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repositorio.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TArquivo
    {
        public System.Guid IdArquivo { get; set; }
        public string Nome { get; set; }
        public decimal TamanhoBytes { get; set; }
        public byte[] Arquivo { get; set; }
        public System.DateTime DataCadastro { get; set; }
        public bool Ativo { get; set; }
    }
}
