//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gerenciador.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRepositorio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRepositorio()
        {
            this.TRepositSistemaCliente = new HashSet<TRepositSistemaCliente>();
        }
    
        public System.Guid IDRepositorio { get; set; }
        public string NomeBaseDados { get; set; }
        public string DadosConexao { get; set; }
        public bool Historica { get; set; }
        public bool ApenasLeitura { get; set; }
        public System.DateTime DataCriacao { get; set; }
        public bool Ativo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRepositSistemaCliente> TRepositSistemaCliente { get; set; }
    }
}
